CREATE TABLE TextileData (
    list INT,
    list_catalogueRef VARCHAR(27) CHARACTER SET utf8,
    list_date VARCHAR(8) CHARACTER SET utf8,
    list_fabricType VARCHAR(9) CHARACTER SET utf8,
    list_item VARCHAR(10) CHARACTER SET utf8,
    list_note VARCHAR(41) CHARACTER SET utf8,
    list_place VARCHAR(16) CHARACTER SET utf8,
    list_source_list INT,
    list_source_list_author_list VARCHAR(16) CHARACTER SET utf8,
    list_source_list_title VARCHAR(63) CHARACTER SET utf8,
    list_source_list_year INT,
    list_spec_list INT,
    list_spec_list_dyeStuff VARCHAR(6) CHARACTER SET utf8,
    list_spec_list_dyeStuff_list VARCHAR(19) CHARACTER SET utf8,
    list_spec_list_observableColour VARCHAR(21) CHARACTER SET utf8,
    list_spec_list_warp INT,
    list_spec_list_warpFleeceType VARCHAR(23) CHARACTER SET utf8,
    list_spec_list_warpTwist VARCHAR(1) CHARACTER SET utf8,
    list_spec_list_weave VARCHAR(28) CHARACTER SET utf8,
    list_spec_list_weft INT,
    list_spec_list_weftFleeceType VARCHAR(23) CHARACTER SET utf8,
    list_spec_list_weftTwist VARCHAR(1) CHARACTER SET utf8
);
INSERT INTO TextileData VALUES (NULL,'1257','850-900','Wool','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Mid Brown',4,'Hairy','Z','Tabby',3,'Hairy','S');
INSERT INTO TextileData VALUES (NULL,'1258','850-900','Wool','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'indigotin','Dark Brown',6,'Hairy','Z','Tabby',5,'Generalised Medium','S');
INSERT INTO TextileData VALUES (NULL,'1259','850-900','Wool','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'indigotin','Black',12,'Hairy','Z','Tabby',8,'Hairy Medium','S');
INSERT INTO TextileData VALUES (NULL,'1260','850-900','Wool','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'madder','Dark Brown',12,'Medium','Z','Tabby',6,'Undetermined','S');
INSERT INTO TextileData VALUES (NULL,'1261','850-900','Wool','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Fawn',15,NULL,'Z','Tabby',9,NULL,'S');
INSERT INTO TextileData VALUES (NULL,'1262','850-900','Wool','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Dark Brown',18,'Medium','Z','Tabby',11,'Medium','S');
INSERT INTO TextileData VALUES (NULL,'1263','850-900','Wool','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Mid Brown',11,'Medium','Z','2/2 twill',11,'Medium','S');
INSERT INTO TextileData VALUES (NULL,'1264','850-900','Wool','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Mottled Brown',18,'Hairy Medium','Z','2/2 chevron twill',11,'Hairy','S');
INSERT INTO TextileData VALUES (NULL,'1265','850-900','Wool','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none',NULL,12,'Medium','Z','2/2 twill',10,'Medium','S');
INSERT INTO TextileData VALUES (NULL,'1266','850-900','Wool','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Mid Brown',14,NULL,'Z','2/2 twill',12,NULL,'S');
INSERT INTO TextileData VALUES (NULL,'1267','850-900','Wool','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Mid Brown',14,'Hairy','Z','2/2 chevron twill',10,'Hairy','S');
INSERT INTO TextileData VALUES (NULL,'1268','850-900','Wool','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Mid Brown',12,NULL,'Z','2/2 diamond twill',10,NULL,'S');
INSERT INTO TextileData VALUES (NULL,'1272','850-900','Veg','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Carbonised',8,NULL,'Z','Tabby',8,NULL,'Z');
INSERT INTO TextileData VALUES (NULL,'1272','850-900','Veg','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Carbonised',8,NULL,'Z','Tabby',8,NULL,'Z');
INSERT INTO TextileData VALUES (NULL,'1273','850-900','Veg','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Carbonised',9,NULL,'Z','2/2 twill',7,NULL,'Z');
INSERT INTO TextileData VALUES (NULL,'1279','900-935','Veg','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Carbonised',13,NULL,'Z','2/2 chevron twill',13,NULL,'Z');
INSERT INTO TextileData VALUES (NULL,'1281','900-935','Silk','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'madder','Mid Brown',20,NULL,'I','Tabby',20,NULL,'I');
INSERT INTO TextileData VALUES (NULL,'1282','900-935','Silk','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Golden Brown',20,NULL,'Z','Tabby',24,NULL,'I');
INSERT INTO TextileData VALUES (NULL,'1295','935-975','Wool','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Dark Brown',5,'Hairy','Z','Tabby',4,'hairy','S');
INSERT INTO TextileData VALUES (NULL,'1296','935-975','Wool','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Grey Brown',3,NULL,'S','Tabby',3,NULL,'S');
INSERT INTO TextileData VALUES (NULL,'1297','935-975','Wool','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Dark Brown',4,'Medium','Z','Tabby',3,'Hairy Medium','S');
INSERT INTO TextileData VALUES (NULL,'1298','935-975','Wool','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Grey Brown',6,NULL,'Z','Tabby',4,NULL,'S');
INSERT INTO TextileData VALUES (NULL,'1299','935-975','Wool','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Dark Brown',14,NULL,'Z','Tabby',8,NULL,'S');
INSERT INTO TextileData VALUES (NULL,'1300','935-975','Wool','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Light Brown',14,'Genralised Medium','Z','Tabby',7,'Hairy','S');
INSERT INTO TextileData VALUES (NULL,'1301','935-975','Wool','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'madder','Red',14,NULL,'Z','2/2 twill',12,NULL,'S');
INSERT INTO TextileData VALUES (NULL,'1302','935-975','Wool','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'indigotin','Mid Brown',8,'Medium','Z','2/2 chevron twill',5,'Hairy','S');
INSERT INTO TextileData VALUES (NULL,'1303','935-975','Wool','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Warp Dark, Weft Light',10,'Hairy','Z','2/2 chevron twill',6,'Hairy Medium','S');
INSERT INTO TextileData VALUES (NULL,'1304','935-975','Wool','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Dark Brown',10,'Hairy','Z','2/2 chevron twill kreuzköper',8,'Hairy Medium','S');
INSERT INTO TextileData VALUES (NULL,'1305','935-975','Wool','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Light Brown',16,'Genralised Medium','Z','2/2 chevron twill',12,'Hairy Medium','S');
INSERT INTO TextileData VALUES (NULL,'1306','935-975','Wool','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'lichen purple','Dull Red',18,'Hairy Medium','Z','2/2 chevron twill',16,'Medium','S');
INSERT INTO TextileData VALUES (NULL,'1307','935-975','Wool','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'lichen purple','Light Brown',11,'Hairy Medium','Z','2/2 diamond twill',7,'Hairy Medium','S');
INSERT INTO TextileData VALUES (NULL,'1308','935-975','Wool','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'madder','Reddish',14,'Medium','Z','2/2 diamond twill',11,'Hairy Medium','S');
INSERT INTO TextileData VALUES (NULL,'1309','935-975','Wool','Sock','Narrow band dyed with madder rest undyed.','York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'madder',NULL,NULL,NULL,'Z','Naalbinding',NULL,NULL,'S');
INSERT INTO TextileData VALUES (NULL,'1317','935-975','Veg','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Carbonised',5,NULL,'Z','Tabby',5,NULL,'S');
INSERT INTO TextileData VALUES (NULL,'1318','935-975','Veg','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Carbonised',5,NULL,'Z','Tabby',6,NULL,'Z');
INSERT INTO TextileData VALUES (NULL,'1319','935-975','Veg','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Carbonised',7,NULL,'Z','Tabby',6,NULL,'Z');
INSERT INTO TextileData VALUES (NULL,'1320','935-975','Veg','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Carbonised',8,NULL,'Z','Tabby',6,NULL,'Z');
INSERT INTO TextileData VALUES (NULL,'1321','935-975','Veg','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Carbonised',10,NULL,'Z','Tabby',7,NULL,'Z');
INSERT INTO TextileData VALUES (NULL,'1322','935-975','Veg','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Carbonised',12,NULL,'Z','Tabby',6,NULL,'Z');
INSERT INTO TextileData VALUES (NULL,'1323','935-975','Veg','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Carbonised',12,NULL,'Z','Tabby',10,NULL,'Z');
INSERT INTO TextileData VALUES (NULL,'1323','935-975','Veg','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Carbonised',12,NULL,'Z','Tabby',10,NULL,'Z');
INSERT INTO TextileData VALUES (NULL,'1324','935-975','Veg','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Carbonised',12,NULL,'Z','Tabby',11,NULL,'Z');
INSERT INTO TextileData VALUES (NULL,'1325','935-975','Veg','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Carbonised',13,NULL,'Z','Tabby',9,NULL,'Z');
INSERT INTO TextileData VALUES (NULL,'1326','935-975','Veg','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Carbonised',14,NULL,'Z','Tabby',12,NULL,'Z');
INSERT INTO TextileData VALUES (NULL,'1327','935-975','Veg','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Carbonised',18,NULL,'Z','Tabby',10,NULL,'Z');
INSERT INTO TextileData VALUES (NULL,'1328','935-975','Veg','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Carbonised',20,NULL,'Z','Tabby',13,NULL,'Z');
INSERT INTO TextileData VALUES (NULL,'1329','935-975','Veg','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Carbonised',24,NULL,'Z','Tabby',18,NULL,'Z');
INSERT INTO TextileData VALUES (NULL,'1330','935-975','Veg','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Mineralised Grey',20,NULL,'Z','Tabby',18,NULL,'Z');
INSERT INTO TextileData VALUES (NULL,'1331','935-975','Veg','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Carbonised',11,NULL,'Z','2/1 twill',8,NULL,'Z');
INSERT INTO TextileData VALUES (NULL,'1332','935-975','Veg','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Carbonised',8,NULL,'Z','2/2 twill',8,NULL,'Z');
INSERT INTO TextileData VALUES (NULL,'1333','935-975','Veg','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Carbonised',11,NULL,'Z','2/1 chevron twill',9,NULL,'Z');
INSERT INTO TextileData VALUES (NULL,'1334','935-975','Veg','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Carbonised',11,NULL,'Z','2/2 chevron twill',9,NULL,'Z');
INSERT INTO TextileData VALUES (NULL,'1335','935-975','Veg','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Carbonised',13,NULL,'Z','2/2 chevron twill',9,NULL,'Z');
INSERT INTO TextileData VALUES (NULL,'1336','935-975','Veg','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Carbonised',15,NULL,'Z','Honeycomb',15,NULL,'Z');
INSERT INTO TextileData VALUES (NULL,'1341','935-975','Silk','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Golden Brown',18,NULL,'Z','Tabby',20,NULL,'I');
INSERT INTO TextileData VALUES (NULL,'1342','935-975','Silk','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'kermes','Dark Brown',18,NULL,'Z','Tabby',23,NULL,'I');
INSERT INTO TextileData VALUES (NULL,'1343','935-975','Silk','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'indigotin','Golden Brown',20,NULL,'Z','Tabby',22,NULL,'I');
INSERT INTO TextileData VALUES (NULL,'1344','935-975','Silk','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Light Brown',20,NULL,'Z','Tabby',24,NULL,'I');
INSERT INTO TextileData VALUES (NULL,'1345','935-975','Silk','Cap',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'madder','Light Brown',24,NULL,'Z','Tabby',20,NULL,'I');
INSERT INTO TextileData VALUES (NULL,'1346','935-975','Silk','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Mid Brown',24,NULL,'Z','Tabby',14,NULL,'Z');
INSERT INTO TextileData VALUES (NULL,'1347','935-975','Silk','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'indigotin','Brown',24,NULL,'Z','Tabby',34,NULL,'I');
INSERT INTO TextileData VALUES (NULL,'1348','935-975','Silk','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Mid Brown',30,NULL,'Z','Tabby',16,NULL,'Z');
INSERT INTO TextileData VALUES (NULL,'1349','935-975','Silk','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'madder','Red Brown',28,NULL,'I',NULL,20,NULL,NULL);
INSERT INTO TextileData VALUES (NULL,'1349','935-975','Silk','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'lichen purple','Red Brown',28,NULL,'I','Tabby',20,NULL,'I');
INSERT INTO TextileData VALUES (NULL,'1350','935-975','Silk','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'madder','Red',24,NULL,'Z','Tabby',14,NULL,'I');
INSERT INTO TextileData VALUES (NULL,'1351','935-975','Silk','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'untested',NULL,40,NULL,'I','Tabby',24,NULL,'I');
INSERT INTO TextileData VALUES (NULL,'1352','935-975','Silk','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'madder','Reddish Brown',60,NULL,'Z',NULL,10,NULL,NULL);
INSERT INTO TextileData VALUES (NULL,'1352','935-975','Silk','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'lichen purple','Reddish Brown',60,NULL,'Z','Tabby',10,NULL,'Z');
INSERT INTO TextileData VALUES (NULL,'1353','935-975','Silk','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'untested','Light Brown',56,NULL,'S','Tabby',26,NULL,'S');
INSERT INTO TextileData VALUES (NULL,'1354','935-975','Silk','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'untested',NULL,56,NULL,'S','Tabby',20,NULL,'S');
INSERT INTO TextileData VALUES (NULL,'1355','935-975','Silk','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,'kermes',NULL,'Mid Brown',48,NULL,'S','Tabby',30,NULL,'S');
INSERT INTO TextileData VALUES (NULL,'1363','975','Veg','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Carbonised',5,NULL,'Z','Tabby',5,NULL,'Z');
INSERT INTO TextileData VALUES (NULL,'1364','975','Veg','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Carbonised',8,NULL,'Z','Tabby',7,NULL,'Z');
INSERT INTO TextileData VALUES (NULL,'1365','975','Veg','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Carbonised',8,NULL,'Z','Tabby',6,NULL,'Z');
INSERT INTO TextileData VALUES (NULL,'1366','975','Veg','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Carbonised',14,NULL,'Z','Tabby',7,NULL,'Z');
INSERT INTO TextileData VALUES (NULL,'1367','975','Veg','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Carbonised',14,NULL,'Z','Tabby',16,NULL,'Z');
INSERT INTO TextileData VALUES (NULL,'1368','975','Veg','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Carbonised',16,NULL,'Z','Tabby',16,NULL,'Z');
INSERT INTO TextileData VALUES (NULL,'1369','975','Veg','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Grey',14,NULL,'Z','Tabby',12,NULL,'Z');
INSERT INTO TextileData VALUES (NULL,'1371','975','Silk','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'madder','Mid Brown',16,NULL,'Z','Tabby',34,NULL,'Z');
INSERT INTO TextileData VALUES (NULL,'1372','975','Silk','Head Dress',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'untested','Golden Brown',24,NULL,'Z','Tabby',19,NULL,'I');
INSERT INTO TextileData VALUES (NULL,'1379','975-1050','Wool','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'madder','Red',7,NULL,'Z','2/2 twill',5,NULL,'S');
INSERT INTO TextileData VALUES (NULL,'1380','975-1050','Wool','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Grey Brown',15,NULL,'Z','2/2 diamond twill',11,NULL,'S');
INSERT INTO TextileData VALUES (NULL,'1381','975-1050','Wool','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'madder','Reddish Grey',14,NULL,'Z','2/2 diamond twill',11,NULL,'S');
INSERT INTO TextileData VALUES (NULL,'1382','975-1050','Wool','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Dark Brown',22,NULL,'Z','2/2 diamond twill',12,NULL,'S');
INSERT INTO TextileData VALUES (NULL,'1388','975-1050','Veg','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Greyish White',24,NULL,'Z','Tabby',20,NULL,'Z');
INSERT INTO TextileData VALUES (NULL,'1389','975-1050','Veg','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Grey Brown',13,NULL,'Z','Tabby',11,NULL,'Z');
INSERT INTO TextileData VALUES (NULL,'1390','975-1050','Veg','Shirt',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Carbonised',22,NULL,'Z','Tabby',18,NULL,'Z');
INSERT INTO TextileData VALUES (NULL,'1391','975-1050','Veg','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Carbonised',10,NULL,'Z','Tabby',6,NULL,'Z');
INSERT INTO TextileData VALUES (NULL,'1392','975-1050','Veg','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Carbonised',10,NULL,'Z','Tabby',8,NULL,'Z');
INSERT INTO TextileData VALUES (NULL,'1393','975-1050','Veg','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Carbonised',17,NULL,'Z','Tabby',10,NULL,'Z');
INSERT INTO TextileData VALUES (NULL,'1394','975-1050','Veg','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Carbonised',14,NULL,'Z','Tabby',8,NULL,'Z');
INSERT INTO TextileData VALUES (NULL,'1395','975-1050','Veg','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Carbonised',20,NULL,'Z','Tabby',16,NULL,'Z');
INSERT INTO TextileData VALUES (NULL,'1396','975-1050','Veg','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Carbonised',16,NULL,'Z','Tabby',14,NULL,'Z');
INSERT INTO TextileData VALUES (NULL,'1397','975-1050','Veg','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Carbonised',8,NULL,'Z','Tabby',5,NULL,'Z');
INSERT INTO TextileData VALUES (NULL,'1398','975-1050','Veg','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Carbonised',20,NULL,'Z','Tabby',15,NULL,'Z');
INSERT INTO TextileData VALUES (NULL,'1399','975-1050','Veg','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Carbonised',20,NULL,'Z','Tabby',20,NULL,'Z');
INSERT INTO TextileData VALUES (NULL,'1400','975-1050','Veg','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Carbonised',26,NULL,'Z','Tabby',28,NULL,'Z');
INSERT INTO TextileData VALUES (NULL,'1401','975-1050','Veg','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Carbonised',22,NULL,'Z','Tabby',20,NULL,'Z');
INSERT INTO TextileData VALUES (NULL,'1402','975-1050','Veg','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Grey',13,NULL,'Z','Tabby',11,NULL,'Z');
INSERT INTO TextileData VALUES (NULL,'1403','975-1050','Veg','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Carbonised',8,NULL,'Z','2/2 twill',8,NULL,'Z');
INSERT INTO TextileData VALUES (NULL,'1404','975-1050','Veg','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Carbonised',15,NULL,'Z','2/2 diamond twill',13,NULL,'Z');
INSERT INTO TextileData VALUES (NULL,'1407','975-1050','Silk','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'madder','Red Brown',42,NULL,'S','Tabby',32,NULL,'S');
INSERT INTO TextileData VALUES (NULL,'1411','700-1100','Wool','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Grey',12,NULL,'Z','Tabby',8,NULL,'S');
INSERT INTO TextileData VALUES (NULL,'1460','700-1100','Wool','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'madder','Mid Brown',5,'Hairy','Z','Tabby',5,'Hairy','S');
INSERT INTO TextileData VALUES (NULL,'1462','700-1100','Veg','Textile',NULL,'York',NULL,'Walton-Rogers, P','Textiles, Cordage and Raw Fibre from 16-22 Coppergate',1989,NULL,NULL,'none','Carbonised',9,NULL,'Z','2/2 twill',7,NULL,'Z');
INSERT INTO TextileData VALUES (NULL,NULL,NULL,'Wool',NULL,NULL,NULL,NULL,'Coatsworth, E','Anglo-Saxon Textiles in the Mayer/Faussett Collection',1998,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO TextileData VALUES (NULL,'Liverpool Museum 6188','450-1100','Wool','Textile',NULL,'Kingston Down',NULL,'Fitzgerald, M','Anglo-Saxon Textiles in the Mayer/Faussett Collection',1998,NULL,NULL,NULL,NULL,14,NULL,'Z','2/2 twill',12,NULL,'S');
INSERT INTO TextileData VALUES (NULL,NULL,NULL,'Wool',NULL,NULL,NULL,NULL,'Coatsworth, E','Anglo-Saxon Textiles in the Mayer/Faussett Collection',1998,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO TextileData VALUES (NULL,'Liverpool Museum AS 14','450-1100','Wool','Textile',NULL,'Sibertswold Down',NULL,'Fitzgerald, M','Anglo-Saxon Textiles in the Mayer/Faussett Collection',1998,NULL,NULL,NULL,NULL,5,NULL,'Z','Tabby',6,NULL,'Z');
INSERT INTO TextileData VALUES (NULL,NULL,NULL,'Veg',NULL,NULL,NULL,NULL,'Coatsworth, E','Anglo-Saxon Textiles in the Mayer/Faussett Collection',1998,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO TextileData VALUES (NULL,'Liverpool Museum AS 9','450-1100','Veg','Textile',NULL,'unknown',NULL,'Fitzgerald, M','Anglo-Saxon Textiles in the Mayer/Faussett Collection',1998,NULL,NULL,NULL,NULL,18,NULL,'Z','Tabby',18,NULL,'Z');
INSERT INTO TextileData VALUES (NULL,NULL,NULL,'Wool',NULL,NULL,NULL,NULL,'Coatsworth, E','Anglo-Saxon Textiles in the Mayer/Faussett Collection',1998,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO TextileData VALUES (NULL,'Liverpool Museum AS 9','450-1100','Wool','Textile',NULL,'unknown',NULL,'Fitzgerald, M','Anglo-Saxon Textiles in the Mayer/Faussett Collection',1998,NULL,NULL,NULL,NULL,6,NULL,'S','2/2 chevron twill',7,NULL,'Z');
INSERT INTO TextileData VALUES (NULL,NULL,NULL,'Wool',NULL,NULL,NULL,NULL,'Coatsworth, E','Anglo-Saxon Textiles in the Mayer/Faussett Collection',1998,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO TextileData VALUES (NULL,'Liverpool Museum AS 8','450-1100','Wool','Textile',NULL,'unknown',NULL,'Fitzgerald, M','Anglo-Saxon Textiles in the Mayer/Faussett Collection',1998,NULL,NULL,NULL,NULL,9,NULL,'Z','2/2 chevron twill',5,NULL,'Z');
INSERT INTO TextileData VALUES (NULL,'1','850-1100','Wool','Textile',NULL,'London',NULL,'Pritchard, F. A','Late Saxon Textiles from the City of London',1984,NULL,NULL,'untested',NULL,6,'Hairy','Z','Tabby',4,'Hairy Medium','S');
INSERT INTO TextileData VALUES (NULL,'2','850-1100','Wool','Textile',NULL,'London',NULL,'Pritchard, F. A','Late Saxon Textiles from the City of London',1984,NULL,NULL,'none',NULL,10,'Hairy medium','Z','Tabby',10,'Generalised Medium','S');
INSERT INTO TextileData VALUES (NULL,'3','850-1100','Wool','Textile',NULL,'London',NULL,'Pritchard, F. A','Late Saxon Textiles from the City of London',1984,NULL,NULL,'madder',NULL,6,'Hairy','Z','Tabby',4,'Medium','S');
INSERT INTO TextileData VALUES (NULL,'4','850-1100','Wool','Textile',NULL,'London',NULL,'Pritchard, F. A','Late Saxon Textiles from the City of London',1984,NULL,NULL,'madder',NULL,3,'Hairy','Z','Tabby',5,'Hairy Medium','Z');
INSERT INTO TextileData VALUES (NULL,'5','850-1100','Wool','Textile',NULL,'London',NULL,'Pritchard, F. A','Late Saxon Textiles from the City of London',1984,NULL,NULL,'untested',NULL,3,'Generalised Medium','Z','Tabby',6,'Generalised Medium','Z');
INSERT INTO TextileData VALUES (NULL,'6','850-1100','Wool','Textile',NULL,'London',NULL,'Pritchard, F. A','Late Saxon Textiles from the City of London',1984,NULL,NULL,'none',NULL,3,'Fine Generalised Medium','Z','Tabby',5,'Fine Generalised Medium','Z');
INSERT INTO TextileData VALUES (NULL,'8','850-1100','Wool','Textile',NULL,'London',NULL,'Pritchard, F. A','Late Saxon Textiles from the City of London',1984,NULL,NULL,'madder',NULL,5,'Hairy Medium','Z','Tabby',3,'Hairy','S');
INSERT INTO TextileData VALUES (NULL,'9','850-1100','Wool','Textile',NULL,'London',NULL,'Pritchard, F. A','Late Saxon Textiles from the City of London',1984,NULL,NULL,'none',NULL,13,NULL,'Z','Tabby',13,NULL,'Z');
INSERT INTO TextileData VALUES (NULL,'10','850-1100','Wool','Textile',NULL,'London',NULL,'Pritchard, F. A','Late Saxon Textiles from the City of London',1984,NULL,NULL,'madder',NULL,11,'Generalised Medium','Z','2/2 lozenge twill',9,'Generalised Medium','S');
INSERT INTO TextileData VALUES (NULL,'11','850-1100','Wool','Textile',NULL,'London',NULL,'Pritchard, F. A','Late Saxon Textiles from the City of London',1984,NULL,NULL,'none',NULL,11,'Hairy Medium','Z','2/2 lozenge twill',10,'Hairy Medium','S');
INSERT INTO TextileData VALUES (NULL,'12','850-1100','Wool','Textile',NULL,'London',NULL,'Pritchard, F. A','Late Saxon Textiles from the City of London',1984,NULL,NULL,'none',NULL,11,'Hairy Medium','Z','2/2 lozenge twill',9,'Hairy Medium','S');
INSERT INTO TextileData VALUES (NULL,'13','850-1100','Wool','Textile',NULL,'London',NULL,'Pritchard, F. A','Late Saxon Textiles from the City of London',1984,NULL,NULL,'none',NULL,14,'Hairy Medium','Z','2/2 lozenge twill',10,'Hairy Medium','S');
INSERT INTO TextileData VALUES (NULL,'14','850-1100','Wool','Textile',NULL,'London',NULL,'Pritchard, F. A','Late Saxon Textiles from the City of London',1984,NULL,NULL,'none',NULL,13,NULL,'Z','2/2 lozenge twill',13,NULL,'S');
INSERT INTO TextileData VALUES (NULL,'15','850-1100','Wool','Textile',NULL,'London',NULL,'Pritchard, F. A','Late Saxon Textiles from the City of London',1984,NULL,NULL,'none',NULL,9,'Hairy Medium','Z','2/2 lozenge twill',6,'Generalised Medium','S');
INSERT INTO TextileData VALUES (NULL,'16','850-1100','Wool','Textile',NULL,'London',NULL,'Pritchard, F. A','Late Saxon Textiles from the City of London',1984,NULL,NULL,'indigotin',NULL,11,'Hairy Medium','Z','2/2 lozenge twill',11,'Hairy Medium','S');
INSERT INTO TextileData VALUES (NULL,'17','850-1100','Wool','Textile',NULL,'London',NULL,'Pritchard, F. A','Late Saxon Textiles from the City of London',1984,NULL,NULL,'madder',NULL,10,'Hairy Medium','Z',NULL,9,NULL,NULL);
INSERT INTO TextileData VALUES (NULL,'17','850-1100','Wool','Textile',NULL,'London',NULL,'Pritchard, F. A','Late Saxon Textiles from the City of London',1984,NULL,NULL,'indigotin',NULL,10,'Hairy Medium','Z','2/2 twill',9,'Hairy','S');
INSERT INTO TextileData VALUES (NULL,'18','850-1100','Wool','Textile',NULL,'London',NULL,'Pritchard, F. A','Late Saxon Textiles from the City of London',1984,NULL,NULL,'none',NULL,15,'Medium','Z','2/2 chevron twill',13,'Medium','S');
INSERT INTO TextileData VALUES (NULL,'19','850-1100','Wool','Textile',NULL,'London',NULL,'Pritchard, F. A','Late Saxon Textiles from the City of London',1984,NULL,NULL,'lichen purple',NULL,15,'Hairy Medium','Z','2/2 chevron twill',14,'Hairy Medium','S');
INSERT INTO TextileData VALUES (NULL,'20','850-1100','Wool','Textile',NULL,'London',NULL,'Pritchard, F. A','Late Saxon Textiles from the City of London',1984,NULL,NULL,'indigotin',NULL,15,'Hairy Medium','Z','2/2 chevron twill',11,'Hairy Medium','S');
INSERT INTO TextileData VALUES (NULL,'21','850-1100','Wool','Textile',NULL,'London',NULL,'Pritchard, F. A','Late Saxon Textiles from the City of London',1984,NULL,NULL,'lichen purple',NULL,15,'Hairy Medium','Z','2/2 chevron twill',13,'Hairy Medium','S');
INSERT INTO TextileData VALUES (NULL,'22','850-1100','Wool','Textile',NULL,'London',NULL,'Pritchard, F. A','Late Saxon Textiles from the City of London',1984,NULL,NULL,'indigotin',NULL,16,'Hairy Medium','Z',NULL,12,NULL,NULL);
INSERT INTO TextileData VALUES (NULL,'22','850-1100','Wool','Textile',NULL,'London',NULL,'Pritchard, F. A','Late Saxon Textiles from the City of London',1984,NULL,NULL,'lichen purple',NULL,16,'Hairy Medium','Z','2/2 chevron twill',12,'Medium','S');
INSERT INTO TextileData VALUES (NULL,'23','850-1100','Wool','Textile',NULL,'London',NULL,'Pritchard, F. A','Late Saxon Textiles from the City of London',1984,NULL,NULL,'none',NULL,14,NULL,'Z','2/2 chevron twill',9,NULL,'S');
INSERT INTO TextileData VALUES (NULL,'24','850-1100','Wool','Textile',NULL,'London',NULL,'Pritchard, F. A','Late Saxon Textiles from the City of London',1984,NULL,NULL,'none',NULL,9,'Hairy Medium','Z','2/2 twill',8,'Hairy Medium','S');
INSERT INTO TextileData VALUES (NULL,'25','850-1100','Wool','Textile',NULL,'London',NULL,'Pritchard, F. A','Late Saxon Textiles from the City of London',1984,NULL,NULL,'none',NULL,4,'Hairy Medium','S','2/1 twill',4,'Hairy Medium','S');
INSERT INTO TextileData VALUES (NULL,'26','850-1100','Wool','Textile',NULL,'London',NULL,'Pritchard, F. A','Late Saxon Textiles from the City of London',1984,NULL,NULL,'none',NULL,9,'Hairy Medium','Z','2/1 twill',9,'Hairy Medium','S');
INSERT INTO TextileData VALUES (NULL,'27','850-1100','Wool','Textile',NULL,'London',NULL,'Pritchard, F. A','Late Saxon Textiles from the City of London',1984,NULL,NULL,'none',NULL,10,'Hairy Medium','Z','2/1 twill',6,'Hairy Medium','S');
INSERT INTO TextileData VALUES (NULL,'28','850-1100','Wool','Textile',NULL,'London',NULL,'Pritchard, F. A','Late Saxon Textiles from the City of London',1984,NULL,NULL,'indigotin',NULL,22,NULL,'Z',NULL,14,NULL,NULL);
INSERT INTO TextileData VALUES (NULL,'28','850-1100','Wool','Textile',NULL,'London',NULL,'Pritchard, F. A','Late Saxon Textiles from the City of London',1984,NULL,NULL,'madder',NULL,22,NULL,'Z','2/1 lozenge twill',14,NULL,'S');
INSERT INTO TextileData VALUES (NULL,'29','850-1100','Wool','Textile',NULL,'London',NULL,'Pritchard, F. A','Late Saxon Textiles from the City of London',1984,NULL,NULL,'none',NULL,28,NULL,'Z','2/1 lozenge twill',19,NULL,'S');
INSERT INTO TextileData VALUES (NULL,'31','850-1100','goat hair','Textile',NULL,'London',NULL,'Pritchard, F. A','Late Saxon Textiles from the City of London',1984,NULL,NULL,'none',NULL,2,NULL,'S','Tabby',2,NULL,'Z');
INSERT INTO TextileData VALUES (NULL,'32','850-1100','goat hair','Textile',NULL,'London',NULL,'Pritchard, F. A','Late Saxon Textiles from the City of London',1984,NULL,NULL,'none',NULL,5,NULL,'S','2/1 twill',4,NULL,'S');
INSERT INTO TextileData VALUES (NULL,'33','850-1100','goat hair','Textile',NULL,'London',NULL,'Pritchard, F. A','Late Saxon Textiles from the City of London',1984,NULL,NULL,'none',NULL,5,NULL,'S','2/1 twill',4,NULL,'S');
INSERT INTO TextileData VALUES (NULL,'34','850-1100','Silk','Textile',NULL,'London',NULL,'Pritchard, F. A','Late Saxon Textiles from the City of London',1984,NULL,NULL,'none',NULL,30,NULL,'Z','Tabby',20,NULL,'I');
INSERT INTO TextileData VALUES (NULL,'35','850-1100','Silk','Textile',NULL,'London',NULL,'Pritchard, F. A','Late Saxon Textiles from the City of London',1984,NULL,NULL,'none',NULL,23,NULL,'Z','Tabby',18,NULL,'I');
INSERT INTO TextileData VALUES (NULL,'34','850-1100','Silk','Textile',NULL,'London',NULL,'Pritchard, F. A','Late Saxon Textiles from the City of London',1984,NULL,NULL,'none',NULL,53,NULL,'I','Tabby',32,NULL,'I');
INSERT INTO TextileData VALUES (NULL,'40','850-1100','Veg','Textile',NULL,'London',NULL,'Pritchard, F. A','Late Saxon Textiles from the City of London',1984,NULL,NULL,'untested',NULL,14,NULL,'Z','Tabby',14,NULL,'Z');
INSERT INTO TextileData VALUES (NULL,'41','850-1100','Veg','Textile',NULL,'London',NULL,'Pritchard, F. A','Late Saxon Textiles from the City of London',1984,NULL,NULL,'untested',NULL,19,NULL,'Z','Tabby',16,NULL,'Z');
INSERT INTO TextileData VALUES (NULL,'OvalBrooch 1 Fragment 1','850-1100','Veg','Textile',NULL,'Kneep',NULL,'Jorgensen, L. B','A Viking burial from Kneep, Uig, Isle of Lewis',1987,NULL,NULL,'untested',NULL,19,NULL,'Z','Tabby',11,NULL,'Z');
INSERT INTO TextileData VALUES (NULL,'OvalBrooch 1 Fragment 2','850-1100','Veg','Textile',NULL,'Kneep',NULL,'Jorgensen, L. B','A Viking burial from Kneep, Uig, Isle of Lewis',1987,NULL,NULL,'untested',NULL,16,NULL,'Z','Tabby',10,NULL,'Z');
INSERT INTO TextileData VALUES (NULL,'OvalBrooch 2 Fragment 1','850-1100','Veg','Textile',NULL,'Kneep',NULL,'Jorgensen, L. B','A Viking burial from Kneep, Uig, Isle of Lewis',1987,NULL,NULL,'untested',NULL,12,NULL,'Z','Tabby',13,NULL,'Z');
INSERT INTO TextileData VALUES (NULL,'OvalBrooch 2 Fragment 2','850-1100','Veg','Textile',NULL,'Kneep',NULL,'Jorgensen, L. B','A Viking burial from Kneep, Uig, Isle of Lewis',1987,NULL,NULL,'untested',NULL,14,NULL,'Z','Tabby',10,NULL,'Z');
INSERT INTO TextileData VALUES (NULL,'Loose','850-1100','Veg','Textile',NULL,'Kneep',NULL,'Jorgensen, L. B','A Viking burial from Kneep, Uig, Isle of Lewis',1987,NULL,NULL,'untested',NULL,10,NULL,'Z','Tabby',11,NULL,'Z');
INSERT INTO TextileData VALUES (NULL,'Loose 2','850-1100','Veg','Textile',NULL,'Kneep',NULL,'Jorgensen, L. B','A Viking burial from Kneep, Uig, Isle of Lewis',1987,NULL,NULL,'untested',NULL,28,NULL,'Z','Tabby',16,NULL,'Z');
INSERT INTO TextileData VALUES (NULL,'Bronze Belt Buckle Fragment','850-1100','Veg','Textile',NULL,'Kneep',NULL,'Jorgensen, L. B','A Viking burial from Kneep, Uig, Isle of Lewis',1987,NULL,NULL,'untested',NULL,32,NULL,'Z','2/2 diamond twill',16,NULL,'Z');
INSERT INTO TextileData VALUES (NULL,NULL,NULL,'Veg',NULL,NULL,NULL,NULL,'Walton-Rogers, P','A Burial of a Viking Woman at Adwick-le-Street, South Yorkshire',2001,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO TextileData VALUES (NULL,'Brooch Fabric','900-1050','Veg','Textile',NULL,'Adwick-le-Street',NULL,'Speed, G','A Burial of a Viking Woman at Adwick-le-Street, South Yorkshire',2001,NULL,NULL,'none',NULL,12,NULL,'Z','Tabby',9,NULL,'Z');
INSERT INTO TextileData VALUES (NULL,NULL,NULL,'Veg',NULL,NULL,NULL,NULL,'Walton-Rogers, P','A Burial of a Viking Woman at Adwick-le-Street, South Yorkshire',2001,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO TextileData VALUES (NULL,'Brooch Loop','900-1050','Veg','Textile',NULL,'Adwick-le-Street',NULL,'Speed, G','A Burial of a Viking Woman at Adwick-le-Street, South Yorkshire',2001,NULL,NULL,'none',NULL,24,NULL,'Z','Tabby',24,NULL,'Z');
INSERT INTO TextileData VALUES (NULL,NULL,NULL,'Wool',NULL,NULL,NULL,NULL,'Carver, M. O. H','Three Saxo-Norman Tenements in Durham City',1974,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO TextileData VALUES (NULL,NULL,NULL,'Wool',NULL,NULL,NULL,NULL,'Crowfoot, E','Three Saxo-Norman Tenements in Durham City',1974,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO TextileData VALUES (NULL,'142/1685/766466','850-1100','Wool','Textile',NULL,'Durham',NULL,'Appleyard, H. M','Three Saxo-Norman Tenements in Durham City',1974,NULL,NULL,'none','Dark Brown',11,NULL,'Z','2/1 twill',7,NULL,'S');
INSERT INTO TextileData VALUES (NULL,NULL,NULL,'Wool',NULL,NULL,NULL,NULL,'Carver, M. O. H','Three Saxo-Norman Tenements in Durham City',1974,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO TextileData VALUES (NULL,NULL,NULL,'Wool',NULL,NULL,NULL,NULL,'Crowfoot, E','Three Saxo-Norman Tenements in Durham City',1974,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO TextileData VALUES (NULL,'166/1685/768413','850-1100','Wool','Textile',NULL,'Durham',NULL,'Appleyard, H. M','Three Saxo-Norman Tenements in Durham City',1974,NULL,NULL,'none','Dark Brown',11,NULL,'I','Felt',7,NULL,'I');
INSERT INTO TextileData VALUES (NULL,NULL,NULL,'Wool',NULL,NULL,NULL,NULL,'Carver, M. O. H','Three Saxo-Norman Tenements in Durham City',1974,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO TextileData VALUES (NULL,NULL,NULL,'Wool',NULL,NULL,NULL,NULL,'Crowfoot, E','Three Saxo-Norman Tenements in Durham City',1974,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO TextileData VALUES (NULL,'17/1575/768410','850-1100','Wool','Textile',NULL,'Durham',NULL,'Appleyard, H. M','Three Saxo-Norman Tenements in Durham City',1974,NULL,NULL,'none','Dark Brown',20,NULL,'Z','2/1 twill',18,NULL,'S');
INSERT INTO TextileData VALUES (NULL,NULL,NULL,'Wool',NULL,NULL,NULL,NULL,'Carver, M. O. H','Three Saxo-Norman Tenements in Durham City',1974,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO TextileData VALUES (NULL,NULL,NULL,'Wool',NULL,NULL,NULL,NULL,'Crowfoot, E','Three Saxo-Norman Tenements in Durham City',1974,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO TextileData VALUES (NULL,'91/1581/766463','850-1100','Wool','Textile',NULL,'Durham',NULL,'Appleyard, H. M','Three Saxo-Norman Tenements in Durham City',1974,NULL,NULL,'Brown Dye (Unknown)','Near Black',15,NULL,'Z','2/1 twill',10,NULL,'S');
INSERT INTO TextileData VALUES (NULL,NULL,NULL,'Wool',NULL,NULL,NULL,NULL,'Carver, M. O. H','Three Saxo-Norman Tenements in Durham City',1974,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO TextileData VALUES (NULL,NULL,NULL,'Wool',NULL,NULL,NULL,NULL,'Crowfoot, E','Three Saxo-Norman Tenements in Durham City',1974,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO TextileData VALUES (NULL,'103/1633/766464','850-1100','Wool','Textile',NULL,'Durham',NULL,'Appleyard, H. M','Three Saxo-Norman Tenements in Durham City',1974,NULL,NULL,'none','Grey Brown',9,NULL,'S','2/1 twill',5,NULL,'Z');
INSERT INTO TextileData VALUES (NULL,NULL,NULL,'Wool',NULL,NULL,NULL,NULL,'Carver, M. O. H','Three Saxo-Norman Tenements in Durham City',1974,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO TextileData VALUES (NULL,NULL,NULL,'Wool',NULL,NULL,NULL,NULL,'Crowfoot, E','Three Saxo-Norman Tenements in Durham City',1974,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO TextileData VALUES (NULL,'121/1639/766465','850-1100','Wool','Textile',NULL,'Durham',NULL,'Appleyard, H. M','Three Saxo-Norman Tenements in Durham City',1974,NULL,NULL,'none','Dark Grey Brown',6,NULL,'Z','2/1 twill',4,NULL,'S');
INSERT INTO TextileData VALUES (NULL,NULL,NULL,'Wool',NULL,NULL,NULL,NULL,'Carver, M. O. H','Three Saxo-Norman Tenements in Durham City',1974,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO TextileData VALUES (NULL,NULL,NULL,'Wool',NULL,NULL,NULL,NULL,'Crowfoot, E','Three Saxo-Norman Tenements in Durham City',1974,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO TextileData VALUES (NULL,'172/1704/768414','850-1100','Wool','Textile',NULL,'Durham',NULL,'Appleyard, H. M','Three Saxo-Norman Tenements in Durham City',1974,NULL,NULL,'none','Plaid',7,NULL,'Z','2/1 twill',8,NULL,'S');
INSERT INTO TextileData VALUES (NULL,NULL,NULL,'Wool',NULL,NULL,NULL,NULL,'Carver, M. O. H','Three Saxo-Norman Tenements in Durham City',1974,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO TextileData VALUES (NULL,NULL,NULL,'Wool',NULL,NULL,NULL,NULL,'Crowfoot, E','Three Saxo-Norman Tenements in Durham City',1974,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO TextileData VALUES (NULL,'179/1744/768415','850-1100','Wool','Textile',NULL,'Durham',NULL,'Appleyard, H. M','Three Saxo-Norman Tenements in Durham City',1974,NULL,NULL,'none','Grey Brown',7,NULL,'S','2/1 twill',4,NULL,'S');
